services:
  - name: flask-hello-world
    type: web
    env: docker
    region: oregon
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "flask run --host=0.0.0.0 --port=5000"
    plan: free
