services:
  - type: web
    name: flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"  # Changed to run the app directly
    plan: free
    branch: main
    autoDeploy: true
